@Simpl.Mobile.Mechanic.Api_HostAddress = http://localhost:5000

POST {{Simpl.Mobile.Mechanic.Api_HostAddress}}/login
Content-Type: application/json

{
    "email": "user@example.com",
    "password": "password123"
}

###
